services:
  db:
    image: postgres:16
    env_file:
      - .env
    container_name: teamfinder_db
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  web:
    build: .
    container_name: teamfinder_web
    env_file:
      - .env
    volumes:
      - .:/app
      - media_data:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data:
  media_data:
